<a href="https://colab.research.google.com/github/shakhzodbekbobobekov/data-science/blob/main/first_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
names = np.array([ "Hasan", "Husan", "Ali", "Vali", "Hasan", "Gani" ])
names

array(['Hasan', 'Husan', 'Ali', 'Vali', 'Hasan', 'Gani'], dtype='<U5')

In [9]:
data = np.random.randn(6,4)
data

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.93084285,  1.64072202,  0.24412124, -0.59858386],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [-0.87309641,  0.93398994, -0.99677291, -0.83669974],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896],
       [-1.44216628, -2.18239872,  0.04421378, -0.92376506]])

In [26]:
mask = (names == "Hasan") | (names == "Ali")

In [28]:
data[ mask ]

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896]])

In [43]:
numbers = np.arange(6)
numbers
arr1 = np.random.randn(6)

In [44]:
qoldiq, butun = np.modf(arr1)

In [45]:
print(qoldiq)
print(butun)

[-0.72730605 -0.03332238  0.68179854  0.99463709 -0.15115814  0.6953751 ]
[-0. -0.  1.  0. -0.  0.]
