<a href="https://colab.research.google.com/github/shakhzodbekbobobekov/data-science/blob/main/first_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [13]:
names = np.array([ "Hasan", "Husan", "Ali", "Vali", "Hasan", "Gani" ])
names

array(['Hasan', 'Husan', 'Ali', 'Vali', 'Hasan', 'Gani'], dtype='<U5')

In [9]:
data = np.random.randn(6,4)
data

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.93084285,  1.64072202,  0.24412124, -0.59858386],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [-0.87309641,  0.93398994, -0.99677291, -0.83669974],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896],
       [-1.44216628, -2.18239872,  0.04421378, -0.92376506]])

In [26]:
mask = (names == "Hasan") | (names == "Ali")

In [28]:
data[ mask ]

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896]])

In [43]:
numbers = np.arange(6)
numbers
arr1 = np.random.randn(6)

In [44]:
qoldiq, butun = np.modf(arr1)

In [45]:
print(qoldiq)
print(butun)

[-0.72730605 -0.03332238  0.68179854  0.99463709 -0.15115814  0.6953751 ]
[-0. -0.  1.  0. -0.  0.]


In [7]:
xarr1 = np.array([ 1.1, 1.2, 1.3, 1.4, 1.5 ])
yarr1 = np.array([ 2.1, 2.2, 2.3, 2.4, 2.5 ])

In [5]:
cond = np.array([ True, False, True, True, False] )

In [8]:
result = np.where(cond, xarr1, yarr1)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
arr = np.random.randn(4,4)
arr

array([[-0.78506178,  1.88687402,  1.15005522,  0.86308514],
       [-0.72238405,  1.37454905,  1.07460523,  0.38293532],
       [ 0.63871958, -0.23018422,  0.46379961,  0.98549798],
       [-0.11747974, -2.08031817,  0.21964857, -0.69663547]])

In [10]:
#where
results = np.where(arr<0, -2, 2)
results

array([[-2,  2,  2,  2],
       [-2,  2,  2,  2],
       [ 2, -2,  2,  2],
       [-2, -2,  2, -2]])

In [19]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

arr1


array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
arr1 * arr2 #bularning mos qiymatlari bir biriga kupaytiriladi.

array([[ 0,  7, 16],
       [27, 40, 55]])

In [13]:
arr3 = np.arange(10).reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
arr3.sum(axis=1) #qatorlarni yigindisini hisoblaydi 0+1+2+3+4=10 // 5+6+7+8+9=35

array([10, 35])

In [15]:
arr3.sum(axis=0) # ustulardi yigindisini hisoblaydi 0+5=5 | 1+6=7 ......

array([ 5,  7,  9, 11, 13])

In [19]:
#urta arifmetik
data3 = np.arange(5)
data3

array([0, 1, 2, 3, 4])

In [20]:
mean1 = np.mean(data3)
mean1 # 0+1+2+3+4=10/5=2

2.0

In [21]:
data3.mean()

2.0