<a href="https://colab.research.google.com/github/shakhzodbekbobobekov/data-science/blob/main/first_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
names = np.array([ "Hasan", "Husan", "Ali", "Vali", "Hasan", "Gani" ])
names

array(['Hasan', 'Husan', 'Ali', 'Vali', 'Hasan', 'Gani'], dtype='<U5')

In [ ]:
data = np.random.randn(6,4)
data

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.93084285,  1.64072202,  0.24412124, -0.59858386],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [-0.87309641,  0.93398994, -0.99677291, -0.83669974],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896],
       [-1.44216628, -2.18239872,  0.04421378, -0.92376506]])

In [ ]:
mask = (names == "Hasan") | (names == "Ali")

In [ ]:
data[ mask ]

array([[ 0.45416968,  1.36120382,  1.08755057,  0.28006359],
       [ 0.41901029,  0.17496528, -0.41230129,  0.6287387 ],
       [ 1.12453526,  0.37258874, -0.26238053, -0.18964896]])

In [ ]:
numbers = np.arange(6)
numbers
arr1 = np.random.randn(6)

In [ ]:
qoldiq, butun = np.modf(arr1)

In [ ]:
print(qoldiq)
print(butun)

[-0.72730605 -0.03332238  0.68179854  0.99463709 -0.15115814  0.6953751 ]
[-0. -0.  1.  0. -0.  0.]


In [ ]:
xarr1 = np.array([ 1.1, 1.2, 1.3, 1.4, 1.5 ])
yarr1 = np.array([ 2.1, 2.2, 2.3, 2.4, 2.5 ])

In [ ]:
cond = np.array([ True, False, True, True, False] )

In [ ]:
result = np.where(cond, xarr1, yarr1)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4,4)
arr

array([[-0.78506178,  1.88687402,  1.15005522,  0.86308514],
       [-0.72238405,  1.37454905,  1.07460523,  0.38293532],
       [ 0.63871958, -0.23018422,  0.46379961,  0.98549798],
       [-0.11747974, -2.08031817,  0.21964857, -0.69663547]])

In [ ]:
#where
results = np.where(arr<0, -2, 2)
results

array([[-2,  2,  2,  2],
       [-2,  2,  2,  2],
       [ 2, -2,  2,  2],
       [-2, -2,  2, -2]])

In [ ]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

arr1


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr1 * arr2 #bularning mos qiymatlari bir biriga kupaytiriladi.

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
arr3 = np.arange(10).reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr3.sum(axis=1) #qatorlarni yigindisini hisoblaydi 0+1+2+3+4=10 // 5+6+7+8+9=35

array([10, 35])

In [ ]:
arr3.sum(axis=0) # ustulardi yigindisini hisoblaydi 0+5=5 | 1+6=7 ......

array([ 5,  7,  9, 11, 13])

In [ ]:
#urta arifmetik
data3 = np.arange(5)
data3

array([0, 1, 2, 3, 4])

In [ ]:
mean1 = np.mean(data3)
mean1 # 0+1+2+3+4=10/5=2

2.0

In [ ]:
data3.mean()

2.0

In [ ]:
arr = np.random.rand(5)
arr

array([0.04121094, 0.85439985, 0.42668501, 0.49990042, 0.46071564])

In [ ]:
sorted_fun = np.sort(arr)
sorted_fun

array([0.04121094, 0.42668501, 0.46071564, 0.49990042, 0.85439985])

In [ ]:
# second method
arr.sort()
arr

array([0.04121094, 0.42668501, 0.46071564, 0.49990042, 0.85439985])

In [ ]:
reverse_arr = -np.sort(-arr)
reverse_arr

array([0.85439985, 0.49990042, 0.46071564, 0.42668501, 0.04121094])

In [ ]:
aaa = np.array([1,2,3,5,8])
print(aaa.ndim)

1


In [ ]:
ab = np.array([[1,2],[3,4]])
print(ab.itemsize)

8


In [5]:
import pandas as pd


In [6]:
import numpy as np

In [8]:
from pandas import Series

In [ ]:
obj = Series([4,5,6, -6.5])

In [ ]:
print(obj.values)

[ 4.   5.   6.  -6.5]


In [ ]:
cars1 = ({"bmw":2000, "amg":202})

In [ ]:
cars1

{'bmw': 2000, 'amg': 202}

In [ ]:
cars2 = Series(cars1)
cars2

bmw    2000
amg     202
dtype: int64

In [ ]:
print(cars2)

bmw    2000
amg     202
dtype: int64


In [ ]:
data = {
    "YIl" : [ 2021, 2022, 2023, 2024 ],
    "AholiSoni" : [ 3.3, 3.2, 3.1, 3 ],
    "Temp": [1.3, 1.2, 1.1, 1]
}

In [ ]:
data

{'YIl': [2021, 2022, 2023, 2024],
 'AholiSoni': [3.3, 3.2, 3.1, 3],
 'Temp': [1.3, 1.2, 1.1, 1]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

YIl  AholiSoni  Temp
0  2021        3.3   1.3
1  2022        3.2   1.2
2  2023        3.1   1.1
3  2024        3.0   1.0

In [ ]:
usernames = { 'anvar': "anvarbek", "olim":"olimtoy", "zuhra":"zuhraoyjon" }
emails = { "anvar":"anvar111@gmail.com", "olim": "olim222@mail.ru", "zuhra": "zuhraoy333@gmail.com"}

In [ ]:
result = Series(emails)
result

anvar      anvar111@gmail.com
olim          olim222@mail.ru
zuhra    zuhraoy333@gmail.com
dtype: object

In [ ]:
data = {
    "usernamess": usernames,
    "emaill": emails
}

df = pd.DataFrame(data)

In [ ]:
df

name  usernamess                emaill
anvar    anvarbek    anvarbek    anvar111@gmail.com
olim      olimtoy     olimtoy       olim222@mail.ru
zuhra  zuhraoyjon  zuhraoyjon  zuhraoy333@gmail.com

In [3]:
usernames = { 'anvar': "anvarbek", "olim":"olimtoy", "zuhra":"zuhraoyjon" }
emails = { "anvar":"anvar111@gmail.com", "olim": "olim222@mail.ru", "zuhra": "zuhraoy333@gmail.com"}

data = {
    "username": usernames,
    "email": emails
}
df1 = pd.DataFrame(data)

In [4]:
usernames = { 'anvar': "anvarbek2", "olim":"olimtoy", "zuhra":"zuhra" }
emails = { "anvar":"anvar200@gmail.com", "olim": "olim200@mail.ru", "zuhra": "zuhraoy2020@gmail.com"}

data2 = {
    "username": usernames,
    "email": emails
}
df2 = pd.DataFrame(data2)

In [11]:
dfresult = pd.concat([df1,df2])
dfresult

username                  email
anvar    anvarbek     anvar111@gmail.com
olim      olimtoy        olim222@mail.ru
zuhra  zuhraoyjon   zuhraoy333@gmail.com
anvar   anvarbek2     anvar200@gmail.com
olim      olimtoy        olim200@mail.ru
zuhra       zuhra  zuhraoy2020@gmail.com